// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pA9Zp3eEKfruzsokkNRlXzP4Nmwt-1c',
    appId: '1:408723214142:web:c74f1d9b8561344ac4266f',
    messagingSenderId: '408723214142',
    projectId: 'tdstimekeeper',
    authDomain: 'tdstimekeeper.firebaseapp.com',
    storageBucket: 'tdstimekeeper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW7ddTLE4L10kHri6SKE2zn0ENGLjGMg4',
    appId: '1:408723214142:android:637376af15bd8250c4266f',
    messagingSenderId: '408723214142',
    projectId: 'tdstimekeeper',
    storageBucket: 'tdstimekeeper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAVP9jwHZ-YPEXnhfOTqdE1G_mo-cTSA',
    appId: '1:408723214142:ios:a5adc1a0378c809ec4266f',
    messagingSenderId: '408723214142',
    projectId: 'tdstimekeeper',
    storageBucket: 'tdstimekeeper.appspot.com',
    iosClientId: '408723214142-feple1lcj3liit7f6r98tsbnsttaslcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdsTimeKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAVP9jwHZ-YPEXnhfOTqdE1G_mo-cTSA',
    appId: '1:408723214142:ios:a5adc1a0378c809ec4266f',
    messagingSenderId: '408723214142',
    projectId: 'tdstimekeeper',
    storageBucket: 'tdstimekeeper.appspot.com',
    iosClientId: '408723214142-feple1lcj3liit7f6r98tsbnsttaslcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdsTimeKeeper',
  );
}
